# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2022-08-01"
# docker_image = "thewawar/ckb-capsule:2022-08-01"

# capsule version
version = "0.9.0"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "perun-channel-lockscript"
template_type = "Rust"

[[contracts]]
name = "perun-channel-typescript"
template_type = "Rust"

[[contracts]]
name = "perun-funds-lockscript"
template_type = "Rust"
